services:
  app:
    image: ghcr.io/devopsdynamite/sinatra-app:dev-latest
    env_file:
      - .env
    volumes:
      - sinatra_data:/app/data
      - sinatra_logs:/app/log
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"

volumes:
  sinatra_data:
  certbot_certs:
  certbot_www:
  sinatra_logs: