services:
  app:
    image: ghcr.io/devopsdynamite/sinatra-app:latest
    env_file:
      - .env
    volumes:
      - sinatra_data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443" # Add port mapping for HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    # Command to run renew check every 12 hours
    # Nginx should pick up renewed certs from the /live/ symlinks
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"

volumes:
  sinatra_data:
  certbot_certs:
  certbot_www:
