# docker-compose.prod.yml

version: '3.8'

services:
  app:
    image: ghcr.io/devopsdynamite/sinatra-app:latest
    env_file:
      - .env
    volumes:
      - sinatra_data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443" # Add port mapping for HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot # Use official Certbot image
    volumes:
      # Mount shared volumes
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  sinatra_data:
  certbot_certs:
  certbot_www:
