# .deepsource.toml

version = 1

[[analyzers]]
name = "ruby"
enabled = true

  [analyzers.meta]
  runtime_version = "3.4.2" 

  
  # Disable the rule preferring assert_not over refute
  Minitest/RefuteInsteadOfAssertNot:
    Enabled: false

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "sinatra/Dockerfile.prod",
    "sinatra/Dockerfile.dev"
  ]

# Example: Excluding a specific check if needed (find check codes on DeepSource docs)
# This is an alternative if the rubocop_config method doesn't work
# You would need to find the specific DeepSource ID for the rule (e.g., "RB-M1016" or similar)
# [analyzers.rules]
# ruby = { skip_checks = ["REPLACE_WITH_DEEPSOURCE_RULE_ID"] }
