name: Continuous Delivery
on:
  push:

    branches: [ "main"] 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow pushing to GHCR (GitHub Packages)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
      - name: Set image tags based on branch
        id: set-tags
        run: |
          # replace every “/” with “-” and force lower‑case just to be safe
          SAFE_BRANCH=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
      
          if [ "$SAFE_BRANCH" = "main" ]; then
            echo "TAGS=ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:latest,ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:${{ github.sha }}" >> "$GITHUB_OUTPUT"
          elif [ "$SAFE_BRANCH" = "dev" ]; then
            echo "TAGS=ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:dev-latest,ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:dev-${{ github.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "TAGS=ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:${SAFE_BRANCH}-latest,ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:${SAFE_BRANCH}-${{ github.sha }}" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: sinatra
          file: sinatra/Dockerfile.prod # use the production Dockerfile
          push: true
          tags: ${{ steps.set-tags.outputs.TAGS }}
          cache-from: type=gha # enable caching of layers to speed up builds
          cache-to: type=gha,mode=max
