name: Continuous Delivery

on:
  push:
    branches: [ "main", "dev", "feature/continuous_delivery" ]  # Trigger on pushes to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allow pushing to GHCR (GitHub Packages)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

    

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.prod          # use the production Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/sinatra-app:${{ github.sha }}
          cache-from: type=gha      # enable caching of layers to speed up builds
          cache-to: type=gha,mode=max
